version: '3.9'
services:
  quest_to_speech:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8091:8000 # predefined in Dockerfile
    volumes:
      - ./tmp:/usr/src/app/data-folder
      - ./.env:/usr/src/app/.env