version: '3.9'
services:
  quest_to_speech:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8090:8081 # predefined in Dockerfile
    volumes:
      - ./tmp:/usr/src/app/data-folder